namespace TrussAnalyzer.Core.Design.ThaiCode;

using TrussAnalyzer.Core.Models;

public sealed class ThaiLoadTemplateProfile
{
    public string ProfileId { get; init; } = "TH-PRELIM-LOADS-2026";
    public string CodeName { get; init; } = "Thai preliminary load templates";
    public string CodeVersion { get; init; } = "Preliminary";
    public IReadOnlyList<string> Assumptions { get; init; } = new[]
    {
        "Templates create named load cases and preliminary load combinations only.",
        "Wind and seismic load magnitudes are not generated by this service.",
        "DL and SDL are treated as permanent gravity loads when combinations use D.",
        "Directional wind and seismic cases are generated separately for traceability."
    };
}

public sealed class ThaiLoadTemplateSet
{
    public ThaiLoadTemplateProfile Profile { get; init; } = new();
    public IReadOnlyList<LoadCase> LoadCases { get; init; } = Array.Empty<LoadCase>();
    public IReadOnlyList<LoadCombination> LoadCombinations { get; init; } = Array.Empty<LoadCombination>();
}

public sealed class ThaiLoadTemplateService
{
    private static readonly string[] WindCaseIds = ["WLX+", "WLX-", "WLY+", "WLY-"];
    private static readonly string[] SeismicCaseIds = ["EQX+", "EQX-", "EQY+", "EQY-"];

    public ThaiLoadTemplateSet GenerateDefaultTemplates(ThaiLoadTemplateProfile? profile = null)
    {
        profile ??= new ThaiLoadTemplateProfile();
        var loadCases = CreateStandardLoadCases(profile).ToList();
        var combinations = CreatePreliminaryCombinations(profile).ToList();
        ValidateCombinationReferences(loadCases, combinations);

        return new ThaiLoadTemplateSet
        {
            Profile = profile,
            LoadCases = loadCases,
            LoadCombinations = combinations
        };
    }

    public ThaiLoadTemplateSet ApplyDefaultTemplates(StructuralModel model, bool replaceExistingCombinations = false, ThaiLoadTemplateProfile? profile = null)
    {
        ArgumentNullException.ThrowIfNull(model);

        var templates = GenerateDefaultTemplates(profile);
        foreach (var loadCase in templates.LoadCases)
        {
            if (model.LoadCases.Any(existing => SameId(existing.CaseId, loadCase.CaseId)))
                continue;

            model.LoadCases.Add(Clone(loadCase));
        }

        foreach (var combination in templates.LoadCombinations)
        {
            int existingIndex = model.LoadCombinations.FindIndex(existing => SameId(existing.CombinationId, combination.CombinationId));
            if (existingIndex >= 0)
            {
                if (replaceExistingCombinations)
                    model.LoadCombinations[existingIndex] = Clone(combination);
                continue;
            }

            model.LoadCombinations.Add(Clone(combination));
        }

        return templates;
    }

    private static IEnumerable<LoadCase> CreateStandardLoadCases(ThaiLoadTemplateProfile profile)
    {
        yield return CreateLoadCase("DL", "Dead Load", LoadCaseType.Static, includeSelfWeight: true, profile, "Permanent structural self-weight and fixed dead load.");
        yield return CreateLoadCase("SDL", "Superimposed Dead Load", LoadCaseType.Static, includeSelfWeight: false, profile, "Permanent non-structural dead load assigned by the user.");
        yield return CreateLoadCase("LL", "Live Load", LoadCaseType.Static, includeSelfWeight: false, profile, "Occupancy live load assigned by the user.");
        yield return CreateLoadCase("RL", "Roof Live Load", LoadCaseType.Static, includeSelfWeight: false, profile, "Roof live load assigned by the user.");

        foreach (string id in WindCaseIds)
            yield return CreateLoadCase(id, $"Wind Load {id}", LoadCaseType.Wind, includeSelfWeight: false, profile, "Directional wind placeholder; magnitude and pressure coefficients are not generated yet.");

        foreach (string id in SeismicCaseIds)
            yield return CreateLoadCase(id, $"Seismic Load {id}", LoadCaseType.Seismic, includeSelfWeight: false, profile, "Directional seismic placeholder; equivalent static base shear is not generated yet.");
    }

    private static IEnumerable<LoadCombination> CreatePreliminaryCombinations(ThaiLoadTemplateProfile profile)
    {
        yield return CreateCombination("SVC-D", "DL + SDL", profile, new Dictionary<string, double> { ["DL"] = 1.0, ["SDL"] = 1.0 }, "Service gravity permanent load.");
        yield return CreateCombination("SVC-DL", "DL + SDL + LL", profile, new Dictionary<string, double> { ["DL"] = 1.0, ["SDL"] = 1.0, ["LL"] = 1.0 }, "Service gravity with occupancy live load.");
        yield return CreateCombination("SVC-DLRL", "DL + SDL + RL", profile, new Dictionary<string, double> { ["DL"] = 1.0, ["SDL"] = 1.0, ["RL"] = 1.0 }, "Service gravity with roof live load.");
        yield return CreateCombination("STR-D", "1.4DL + 1.4SDL", profile, new Dictionary<string, double> { ["DL"] = 1.4, ["SDL"] = 1.4 }, "Preliminary strength gravity permanent load.");
        yield return CreateCombination("STR-DL", "1.2DL + 1.2SDL + 1.6LL + 0.5RL", profile, new Dictionary<string, double> { ["DL"] = 1.2, ["SDL"] = 1.2, ["LL"] = 1.6, ["RL"] = 0.5 }, "Preliminary strength gravity load.");
        yield return CreateCombination("STR-DRL", "1.2DL + 1.2SDL + 1.6RL + 0.5LL", profile, new Dictionary<string, double> { ["DL"] = 1.2, ["SDL"] = 1.2, ["RL"] = 1.6, ["LL"] = 0.5 }, "Preliminary roof-governing strength load.");

        foreach (string id in WindCaseIds)
        {
            yield return CreateCombination($"SVC-{id}", $"DL + SDL + 0.75LL + 0.75{id}", profile, new Dictionary<string, double> { ["DL"] = 1.0, ["SDL"] = 1.0, ["LL"] = 0.75, [id] = 0.75 }, "Preliminary service wind combination.");
            yield return CreateCombination($"STR-{id}", $"1.2DL + 1.2SDL + 1.0LL + 1.0{id}", profile, new Dictionary<string, double> { ["DL"] = 1.2, ["SDL"] = 1.2, ["LL"] = 1.0, [id] = 1.0 }, "Preliminary strength wind combination.");
            yield return CreateCombination($"UPL-{id}", $"0.9DL + 0.9SDL + 1.0{id}", profile, new Dictionary<string, double> { ["DL"] = 0.9, ["SDL"] = 0.9, [id] = 1.0 }, "Preliminary uplift/overturning wind combination.");
        }

        foreach (string id in SeismicCaseIds)
        {
            yield return CreateCombination($"SVC-{id}", $"DL + SDL + 0.25LL + 1.0{id}", profile, new Dictionary<string, double> { ["DL"] = 1.0, ["SDL"] = 1.0, ["LL"] = 0.25, [id] = 1.0 }, "Preliminary service seismic combination.");
            yield return CreateCombination($"STR-{id}", $"1.2DL + 1.2SDL + 1.0LL + 1.0{id}", profile, new Dictionary<string, double> { ["DL"] = 1.2, ["SDL"] = 1.2, ["LL"] = 1.0, [id] = 1.0 }, "Preliminary strength seismic combination.");
            yield return CreateCombination($"UPL-{id}", $"0.9DL + 0.9SDL + 1.0{id}", profile, new Dictionary<string, double> { ["DL"] = 0.9, ["SDL"] = 0.9, [id] = 1.0 }, "Preliminary uplift/overturning seismic combination.");
        }
    }

    private static LoadCase CreateLoadCase(string id, string name, LoadCaseType type, bool includeSelfWeight, ThaiLoadTemplateProfile profile, string description)
    {
        return new LoadCase
        {
            CaseId = id,
            Name = name,
            Type = type,
            IncludeSelfWeight = includeSelfWeight,
            Description = $"{description} Source={profile.ProfileId}; {profile.CodeName} ({profile.CodeVersion})."
        };
    }

    private static LoadCombination CreateCombination(string id, string name, ThaiLoadTemplateProfile profile, Dictionary<string, double> factors, string description)
    {
        return new LoadCombination
        {
            CombinationId = id,
            Name = name,
            LoadCases = factors,
            Description = $"{description} Source={profile.ProfileId}; preliminary template factors only."
        };
    }

    private static void ValidateCombinationReferences(IEnumerable<LoadCase> loadCases, IEnumerable<LoadCombination> combinations)
    {
        var caseIds = loadCases.Select(lc => lc.CaseId).ToHashSet(StringComparer.OrdinalIgnoreCase);
        foreach (var combination in combinations)
        {
            foreach (string referencedCaseId in combination.LoadCases.Keys)
            {
                if (!caseIds.Contains(referencedCaseId))
                    throw new InvalidOperationException($"Thai load template '{combination.CombinationId}' references missing load case '{referencedCaseId}'.");
            }
        }
    }

    private static LoadCase Clone(LoadCase source)
    {
        return new LoadCase
        {
            CaseId = source.CaseId,
            Name = source.Name,
            Type = source.Type,
            IncludeSelfWeight = source.IncludeSelfWeight,
            LoadFactor = source.LoadFactor,
            Description = source.Description,
            CreatedDate = source.CreatedDate,
            NodeForces = source.NodeForces.ToDictionary(kvp => kvp.Key, kvp => new ForceVector(kvp.Value.Fx, kvp.Value.Fy, kvp.Value.Fz))
        };
    }

    private static LoadCombination Clone(LoadCombination source)
    {
        return new LoadCombination
        {
            CombinationId = source.CombinationId,
            Name = source.Name,
            Description = source.Description,
            LoadCases = source.LoadCases.ToDictionary(kvp => kvp.Key, kvp => kvp.Value, StringComparer.OrdinalIgnoreCase)
        };
    }

    private static bool SameId(string left, string right)
    {
        return string.Equals(left, right, StringComparison.OrdinalIgnoreCase);
    }
}

